/**
 * WordPress Post/Page Creation/Update POC
 *
 * This is a throwaway POC to test creating/updating WordPress posts/pages
 * with race results.
 *
 * Prerequisites:
 * 1. Install node-fetch: npm install node-fetch@2
 *
 * Usage:
 * node wordpress-poc.cjs
 */

const fetch = require('node-fetch');

// Configuration from .env.local
const WORDPRESS_URL = 'https://berowrabushrunners.com';
const USERNAME = 'ara.mailbox+bushrun@gmail.com';
const APP_PASSWORD = 'Pd3T eRks xmfq mC6U wHs7 LrmV';

// Create Basic Auth header
const authHeader = 'Basic ' + Buffer.from(`${USERNAME}:${APP_PASSWORD}`).toString('base64');

// Sample race results data
const sampleRaceResults = {
  raceName: "Bushrun Championship 2024",
  date: "2024-03-15",
  results: [
    { position: 1, name: "John Smith", time: "18:23", handicap: "+2:15", club: "City Runners" },
    { position: 2, name: "Jane Doe", time: "19:45", handicap: "+1:30", club: "Marathon Club" },
    { position: 3, name: "Bob Johnson", time: "20:12", handicap: "+0:45", club: "City Runners" }
  ]
};

/**
 * Generate HTML content for race results
 */
function generateRaceResultsHTML(raceData) {
  const resultsRows = raceData.results
    .map(r => `
      <tr>
        <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">${r.position}</td>
        <td style="padding: 12px; border-bottom: 1px solid #e5e7eb; font-weight: 600;">${r.name}</td>
        <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">${r.time}</td>
        <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">${r.handicap}</td>
        <td style="padding: 12px; border-bottom: 1px solid #e5e7eb;">${r.club}</td>
      </tr>
    `)
    .join('');

  return `
    <div style="max-width: 800px; margin: 0 auto; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;">
      <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 32px; border-radius: 8px 8px 0 0;">
        <h1 style="margin: 0 0 8px 0; font-size: 32px;">${raceData.raceName}</h1>
        <p style="margin: 0; opacity: 0.9; font-size: 18px;">${raceData.date}</p>
      </div>

      <div style="background: white; padding: 24px; border-radius: 0 0 8px 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">
        <table style="width: 100%; border-collapse: collapse;">
          <thead>
            <tr style="background-color: #f9fafb;">
              <th style="padding: 12px; text-align: left; font-weight: 600; color: #374151; border-bottom: 2px solid #e5e7eb;">Pos</th>
              <th style="padding: 12px; text-align: left; font-weight: 600; color: #374151; border-bottom: 2px solid #e5e7eb;">Runner</th>
              <th style="padding: 12px; text-align: left; font-weight: 600; color: #374151; border-bottom: 2px solid #e5e7eb;">Time</th>
              <th style="padding: 12px; text-align: left; font-weight: 600; color: #374151; border-bottom: 2px solid #e5e7eb;">Handicap</th>
              <th style="padding: 12px; text-align: left; font-weight: 600; color: #374151; border-bottom: 2px solid #e5e7eb;">Club</th>
            </tr>
          </thead>
          <tbody>
            ${resultsRows}
          </tbody>
        </table>
      </div>

      <div style="margin-top: 24px; padding: 16px; background: #f9fafb; border-radius: 8px; text-align: center;">
        <p style="margin: 0; color: #6b7280; font-size: 14px;">
          Results generated by Bushrun Race Day App
        </p>
      </div>
    </div>
  `;
}

/**
 * Get current user info
 */
async function getCurrentUser() {
  try {
    const response = await fetch(`${WORDPRESS_URL}/wp-json/wp/v2/users/me`, {
      headers: {
        'Authorization': authHeader
      }
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(`Failed to get user: ${JSON.stringify(error)}`);
    }

    return await response.json();
  } catch (error) {
    console.error('❌ Error getting user:', error.message);
    throw error;
  }
}

/**
 * Create a new WordPress post (not page)
 */
async function createWordPressPost(title, content, categories = []) {
  try {
    const response = await fetch(`${WORDPRESS_URL}/wp-json/wp/v2/posts`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': authHeader
      },
      body: JSON.stringify({
        title: title,
        content: content,
        status: 'publish', // or 'draft' to create as draft
        categories: categories
      })
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(`Failed to create post: ${JSON.stringify(error)}`);
    }

    const data = await response.json();
    console.log('✅ Post created successfully!');
    console.log(`   ID: ${data.id}`);
    console.log(`   URL: ${data.link}`);
    return data;
  } catch (error) {
    console.error('❌ Error creating post:', error.message);
    throw error;
  }
}

/**
 * Create a new WordPress page
 */
async function createWordPressPage(title, content) {
  try {
    const response = await fetch(`${WORDPRESS_URL}/wp-json/wp/v2/pages`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': authHeader
      },
      body: JSON.stringify({
        title: title,
        content: content,
        status: 'publish' // or 'draft' to create as draft
      })
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(`Failed to create page: ${JSON.stringify(error)}`);
    }

    const data = await response.json();
    console.log('✅ Page created successfully!');
    console.log(`   ID: ${data.id}`);
    console.log(`   URL: ${data.link}`);
    return data;
  } catch (error) {
    console.error('❌ Error creating page:', error.message);
    throw error;
  }
}

/**
 * Update an existing WordPress page
 */
async function updateWordPressPage(pageId, title, content) {
  try {
    const response = await fetch(`${WORDPRESS_URL}/wp-json/wp/v2/pages/${pageId}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': authHeader
      },
      body: JSON.stringify({
        title: title,
        content: content
      })
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(`Failed to update page: ${JSON.stringify(error)}`);
    }

    const data = await response.json();
    console.log('✅ Page updated successfully!');
    console.log(`   ID: ${data.id}`);
    console.log(`   URL: ${data.link}`);
    return data;
  } catch (error) {
    console.error('❌ Error updating page:', error.message);
    throw error;
  }
}

/**
 * Find a page by title
 */
async function findPageByTitle(title) {
  try {
    const response = await fetch(
      `${WORDPRESS_URL}/wp-json/wp/v2/pages?search=${encodeURIComponent(title)}`,
      {
        headers: {
          'Authorization': authHeader
        }
      }
    );

    if (!response.ok) {
      throw new Error('Failed to search pages');
    }

    const pages = await response.json();
    return pages.length > 0 ? pages[0] : null;
  } catch (error) {
    console.error('❌ Error searching pages:', error.message);
    return null;
  }
}

/**
 * Find a post by title
 */
async function findPostByTitle(title) {
  try {
    const response = await fetch(
      `${WORDPRESS_URL}/wp-json/wp/v2/posts?search=${encodeURIComponent(title)}`,
      {
        headers: {
          'Authorization': authHeader
        }
      }
    );

    if (!response.ok) {
      throw new Error('Failed to search posts');
    }

    const posts = await response.json();
    return posts.length > 0 ? posts[0] : null;
  } catch (error) {
    console.error('❌ Error searching posts:', error.message);
    return null;
  }
}

/**
 * Update an existing WordPress post
 */
async function updateWordPressPost(postId, title, content) {
  try {
    const response = await fetch(`${WORDPRESS_URL}/wp-json/wp/v2/posts/${postId}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': authHeader
      },
      body: JSON.stringify({
        title: title,
        content: content
      })
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(`Failed to update post: ${JSON.stringify(error)}`);
    }

    const data = await response.json();
    console.log('✅ Post updated successfully!');
    console.log(`   ID: ${data.id}`);
    console.log(`   URL: ${data.link}`);
    return data;
  } catch (error) {
    console.error('❌ Error updating post:', error.message);
    throw error;
  }
}

/**
 * Main POC function
 */
async function runPOC() {
  console.log('🚀 WordPress Page Creation POC\n');

  // First, check user capabilities
  console.log('👤 Checking current user...');
  try {
    const user = await getCurrentUser();
    console.log(`   Logged in as: ${user.name} (${user.slug})`);
    console.log(`   Roles: ${user.roles?.join(', ') || 'none'}\n`);
  } catch (error) {
    console.log('   Could not get user info\n');
  }

  // Generate HTML content
  const htmlContent = generateRaceResultsHTML(sampleRaceResults);
  const pageTitle = `${sampleRaceResults.raceName} - Results`;

  // Try creating a page
  console.log('📝 Checking if page already exists...');
  const existingPage = await findPageByTitle(pageTitle);

  if (existingPage) {
    console.log(`   Found existing page with ID: ${existingPage.id}\n`);
    console.log('🔄 Updating existing page...');
    await updateWordPressPage(existingPage.id, pageTitle, htmlContent);
  } else {
    console.log('   No existing page found\n');
    console.log('➕ Creating new page...');
    await createWordPressPage(pageTitle, htmlContent);
  }

  console.log('\n✨ POC completed successfully!');
}

// Run the POC
if (require.main === module) {
  runPOC().catch(error => {
    console.error('\n💥 POC failed:', error);
    process.exit(1);
  });
}

// Export functions for use in other modules
module.exports = {
  getCurrentUser,
  createWordPressPost,
  updateWordPressPost,
  findPostByTitle,
  createWordPressPage,
  updateWordPressPage,
  findPageByTitle,
  generateRaceResultsHTML
};
